baseURL = 'https://shubhamlad.in/'
languageCode = 'en-us'
title = 'Shubham Lad'
theme = 'paper'

[params]
  # home page profile
  avatar = 'shubhamlad1001@gmail.com'                 # gravatar email or image url
  name = 'Brief Description'
  images = ['https://drive.google.com/uc?id=11cn1SC-hMlLKUvqtXb6TCmgrZAFLdVAG']
  title = 'Shubham Lad | Sr. Software Engineer'
  description = 'Explore the tech world with Shubham, a Senior Software Engineer. Unravel System Designs, Database, Networks, and more. Grab a coffee, get comfy, and let's dive into software together!'

[markup]
  defaultMarkdownHandler = 'goldmark'

[markup.goldmark.parser.attribute]
block = true
title = true

[menu]
  # [[menu.main]]
  #   name = '📋 Notes'
  #   url = 'https://notes.shubhamlad.in'
  #   weight = 20
  [[menu.main]]
    name = '📝 Blog'
    pageRef = '/blog'
    weight = 20